version: build-{build}.{branch}

platform: x64

clone_folder: c:\gopath\src\github.com\nu11ptr\cliexpect

environment:
  GOPATH: c:\gopath

build: false
deploy: false

before_test:
  - go vet ./...

test_script:
  - go test -v -race ./...
