version: build-{build}.{branch}

platform: x64

clone_folder: c:\gopath\src\github.com\$username\$project

environment:
  GOPATH: c:\gopath

build: false
deploy: false

before_test:
  - go vet ./...

test_script:
  - go test -v -race ./...
